attendee/reg route update
ReflectionsProjections/rp-api pull request #73
Opened 2024-05-30 02:23 UTC by jacobc2700

2024-05-30 05:20 UTC, AydanPirani requested changes
a few changes, but lgtm otherwise!

2024-05-30 05:20 UTC, AydanPirani commented on src/services/events/events-router.ts
> +        }
can this not all be cleaned up in one go: 

indOne({
    startTime: { $gte: now }
  }).sort({ startTime: 1 });

2024-05-30 05:20 UTC, AydanPirani commented on src/services/events/events-schema.ts
> +export const EventType = z.enum(events);
```suggestion
export const EventType = z.enum(["A", "B", "C"]);
```

2024-05-30 05:20 UTC, AydanPirani commented on src/services/events/events-schema.ts
> +        enum: events,
EventType.Values

2024-05-30 06:32 UTC, AydanPirani reviewed
lgtm! @divyack2  waiting on ur final approval

2024-05-31 02:29 UTC, divyack2 commented on src/services/events/events-schema.ts
> +export const EventType = z.enum(["A", "B", "C"]);
wait should this be named with like CORPORATE, SPEAKER, etc instead of A, B, C?

2024-06-02 20:57 UTC, AydanPirani approved these changes

2024-06-02 20:58 UTC, merged